name: Build and Push Custom Collabora

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull upstream image
        run: docker pull collabora/code:latest

      - name: Get upstream image digest
        id: upstream_digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' collabora/code:latest)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Download last digest artifact
        uses: actions/download-artifact@v4
        with:
          name: last-digest
        continue-on-error: true

      - name: Read last digest
        id: last_digest
        run: |
          if [ -f digest.txt ]; then
            echo "last_digest=$(cat digest.txt)" >> $GITHUB_OUTPUT
          else
            echo "last_digest=none" >> $GITHUB_OUTPUT
          fi

      - name: Check if build is needed
        id: check
        run: |
          if [ "${{ steps.upstream_digest.outputs.digest }}" = "${{ steps.last_digest.outputs.last_digest }}" ]; then
            echo "No changes in upstream image. Skipping build."
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Upstream image changed. Building!"
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GHCR
        if: steps.check.outputs.build_needed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: reniko # dein GitHub Username
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        if: steps.check.outputs.build_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        if: steps.check.outputs.build_needed == 'true'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/reniko/collabora-custom:latest

      - name: Upload new digest
        if: steps.check.outputs.build_needed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: last-digest
          path: |
            digest.txt
        run: echo "${{ steps.upstream_digest.outputs.digest }}" > digest.txt
